<?php

namespace AppBundle\Repository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getlevels(){
//        Alias 'l' = Level

        $qb = $this->createQueryBuilder('l')
            ->select('l.id', 'l.levelName')
            ->orderBy('l.id', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
