<?php

namespace AppBundle\Repository;

/**
 * SideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SideRepository extends \Doctrine\ORM\EntityRepository
{
}
