app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
#-------------------------------------------------------
#------------------------- ADMINISTRATION
#-------------------------------------------------------

app_admin:
    path:     /administration
    defaults: { _controller: "AppBundle:Default:Admin" }
    methods:  GET

#-------------------------------------------------------
#------------------------- CRUD
#-------------------------------------------------------

app_level:
    resource: "@AppBundle/Resources/config/routing/level.yml"
    prefix:   /level
    
app_side:
    resource: "@AppBundle/Resources/config/routing/side.yml"
    prefix:   /side
    
app_society:
    resource: "@AppBundle/Resources/config/routing/society.yml"
    prefix:   /society

app_carousel:
    resource: "@AppBundle/Resources/config/routing/carousel.yml"
    prefix:   /carousel
