app:
    resource: '@AppBundle/Controller/'
    type: annotation

#-------------------------------------------------------
#------------------------- CRUD
#-------------------------------------------------------

app_level:
    resource: "@AppBundle/Resources/config/routing/level.yml"
    prefix:   /level
    
app_side:
    resource: "@AppBundle/Resources/config/routing/side.yml"
    prefix:   /side
    
app_society:
    resource: "@AppBundle/Resources/config/routing/society.yml"
    prefix:   /society
