carousel_index:
    path:     /
    defaults: { _controller: "AppBundle:Carousel:index" }
    methods:  GET

carousel_show:
    path:     /
    defaults: { _controller: "AppBundle:Carousel:RederingCarousel" }
    methods:  GET

carousel_new:
    path:     /new
    defaults: { _controller: "AppBundle:Carousel:new" }
    methods:  [GET, POST]

carousel_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Carousel:edit" }
    methods:  [GET, POST]

carousel_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Carousel:delete" }
    methods:  DELETE
