side_index:
    path:     /
    defaults: { _controller: "AppBundle:Side:index" }
    methods:  GET

side_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Side:show" }
    methods:  GET

side_new:
    path:     /new
    defaults: { _controller: "AppBundle:Side:new" }
    methods:  [GET, POST]

side_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Side:edit" }
    methods:  [GET, POST]

side_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Side:delete" }
    methods:  DELETE
