society_index:
    path:     /
    defaults: { _controller: "AppBundle:Society:index" }
    methods:  GET

society_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Society:show" }
    methods:  GET

society_new:
    path:     /new
    defaults: { _controller: "AppBundle:Society:new" }
    methods:  [GET, POST]

society_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Society:edit" }
    methods:  [GET, POST]

society_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Society:delete" }
    methods:  DELETE
