AppBundle\Entity\Level:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LevelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        levelName:
            type: string
            length: '30'
            unique: true
            column: level_name

    oneToMany:
        society:
            targetEntity: AppBundle\Entity\Society
            mappedBy: levels

    lifecycleCallbacks: {  }
