AppBundle\Entity\Society:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SocietyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        societyName:
            type: string
            length: '30'
            column: society_name

    manyToOne:
        levels:
            targetEntity: AppBundle\Entity\Level
            inversedBy: society
            joinColumn:
                name: level_id
                referencedColumnName: id
        side:
            targetEntity: AppBundle\Entity\Side
            inversedBy: society
            joinColumn:
                name: side_id
                referencedColumnName: id
    oneToOne:
        media:
            targetEntity: AppBundle\Entity\Media
            cascade: ['all']

    lifecycleCallbacks: {  }
